name: Scheduled LATEST_STABLE

on:
  schedule:
    - cron: 15 22,21 10,1,15 * *

jobs:
  call-workflow-stable:
    uses: ./.github/workflows/build.yml
    with:
      version_type: LATEST_STABLE
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
  call-workflow-beta:
    uses: ./.github/workflows/build.yml
    with:
      version_type: LATEST_BETA
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
